import type { DiscoveredOffer } from "@/lib/discovery/types";

// A hand-verified snapshot of live US checking sign-up bonuses (July 2026),
// gathered from public trackers (Doctor of Credit, NerdWallet, Bankrate, CNBC)
// and bank offer pages. Money in integer cents.
//
// Every entry carries a precise `applicationUrl` + `applicationChannel` and a
// `signupNotes` string describing THAT bank's direct-deposit rules — the #1
// reason a bonus fails. High-confidence entries (>=0.75) are cross-checked
// across sources; anything lower is flagged `unverified`. Fabricated/padded
// rows from the previous pass (Betterment, Upgrade, LendingClub, Axos, Laurel
// Road) were removed; Varo was corrected to its real app-only terms. Nothing
// here is financial advice — confirm fine print at the source before acting.

const c = (dollars: number) => Math.round(dollars * 100);

const DOC = "https://www.doctorofcredit.com/best-bank-account-bonuses/";
const STRICT_DD =
  "Only payroll / pension / government-benefit ACH counts as a direct deposit. External bank transfers, Zelle/P2P, mobile check deposits, and wires do NOT qualify.";
const LENIENT_DD =
  "Most recurring ACH deposits count, but set up a true employer/payroll direct deposit to be safe.";

export const CURATED_OFFERS: DiscoveredOffer[] = [
  // ---- National / nationwide-eligible (incl. Georgia), web application ----
  {
    brandName: "Chase",
    legalName: "JPMorgan Chase Bank, N.A.",
    charterType: "national_bank",
    hqState: "OH",
    chexsystemsSensitivity: "strict",
    earlyClosureClawbackDays: 180,
    productName: "Chase Total Checking",
    productType: "checking",
    monthlyFeeCents: c(12),
    minOpeningDepositCents: 0,
    accountOpeningUrl: "https://account.chase.com/consumer/banking/seo",
    applicationUrl: "https://account.chase.com/consumer/banking/seo",
    applicationChannel: "web",
    signupNotes: STRICT_DD + " Enroll through the coupon page; the 90-day clock starts at enrollment.",
    title: "Chase Total Checking — $400 bonus",
    offerCode: "coupon",
    bonusType: "cash",
    bonusAmountCents: c(400),
    offerEndDate: "2026-10-14",
    requirementWindowDays: 90,
    payoutWindowDays: 15,
    newCustomerRequired: true,
    customerLookbackMonths: 24,
    termsUrl: "https://account.chase.com/consumer/banking/seo",
    sourceUrl: "https://www.doctorofcredit.com/chase-400-checking-bonus/",
    extractionConfidence: 0.92,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(1000),
        windowDays: 90,
        depositSourceConstraint: "payroll_ach",
        verificationDifficulty: "probabilistic",
        confidenceNotes: STRICT_DD,
      },
    ],
    disqualifiers: [
      {
        disqualifierType: "existing_customer",
        lookbackMonths: 24,
        detail: "Not for existing Chase checking customers; one bonus per 2 years.",
      },
      {
        disqualifierType: "closed_account_lookback",
        lookbackMonths: 36,
        detail: "Ineligible if you closed a Chase account with a negative balance in 3 years.",
      },
    ],
  },
  {
    brandName: "SoFi",
    legalName: "SoFi Bank, N.A.",
    charterType: "national_bank",
    hqState: "CA",
    chexsystemsSensitivity: "none",
    earlyClosureClawbackDays: 0,
    productName: "SoFi Checking and Savings",
    productType: "checking",
    monthlyFeeCents: 0,
    standardApyBps: 360,
    accountOpeningUrl: "https://www.sofi.com/banking/checking-offer/",
    applicationUrl: "https://www.sofi.com/banking/checking-offer/",
    applicationChannel: "web",
    signupNotes:
      LENIENT_DD + " $1,000 DD tier pays $50; $5,000+ within 25 days pays the full $400.",
    title: "SoFi Checking and Savings — up to $400 bonus",
    bonusType: "cash",
    bonusAmountCents: c(400),
    offerEndDate: "2026-12-31",
    requirementWindowDays: 25,
    payoutWindowDays: 7,
    newCustomerRequired: false,
    termsUrl: "https://www.sofi.com/banking/checking-offer/",
    sourceUrl:
      "https://finance.yahoo.com/personal-finance/banking/article/new-bank-account-bonuses-214704427.html",
    extractionConfidence: 0.9,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(5000),
        windowDays: 25,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
        confidenceNotes: LENIENT_DD,
      },
    ],
    disqualifiers: [
      {
        disqualifierType: "prior_bonus_lookback",
        detail: "Only for members who have not previously enrolled in SoFi direct deposit.",
      },
    ],
  },
  {
    brandName: "Capital One",
    legalName: "Capital One, N.A.",
    charterType: "national_bank",
    hqState: "VA",
    chexsystemsSensitivity: "none",
    productName: "Capital One 360 Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.capitalone.com/bank/checking-accounts/",
    applicationUrl: "https://www.capitalone.com/bank/checking-accounts/",
    applicationChannel: "web",
    signupNotes: "Two direct deposits of at least $500 each within 75 days. Standard payroll/gov DD.",
    title: "Capital One 360 Checking — $250 bonus",
    bonusType: "cash",
    bonusAmountCents: c(250),
    requirementWindowDays: 75,
    payoutWindowDays: 60,
    newCustomerRequired: true,
    termsUrl: "https://www.capitalone.com/bank/checking-accounts/",
    sourceUrl: DOC,
    extractionConfidence: 0.8,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(1000),
        targetCount: 2,
        windowDays: 75,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
        confidenceNotes: "Two direct deposits of at least $500 each within 75 days.",
      },
    ],
  },
  {
    brandName: "U.S. Bank",
    legalName: "U.S. Bank National Association",
    charterType: "national_bank",
    hqState: "MN",
    chexsystemsSensitivity: "moderate",
    productName: "U.S. Bank Smartly Checking",
    productType: "checking",
    monthlyFeeCents: c(6.95),
    minOpeningDepositCents: c(25),
    accountOpeningUrl: "https://www.usbank.com/bank-accounts/checking-accounts.html",
    applicationUrl: "https://www.usbank.com/bank-accounts/checking-accounts.html",
    applicationChannel: "web",
    signupNotes:
      "Tiered by total DD in 90 days: $5,000–$7,999 earns $350; higher tiers up to $450. Make the $25 opening deposit within 60 days.",
    title: "U.S. Bank Smartly Checking — up to $450 bonus",
    bonusType: "cash",
    bonusAmountCents: c(350),
    requirementWindowDays: 90,
    payoutWindowDays: 30,
    newCustomerRequired: true,
    customerLookbackMonths: 12,
    termsUrl: "https://www.usbank.com/splash/checking-bonus.html",
    sourceUrl: "https://www.forbes.com/advisor/banking/us-bank-promotions-bonus/",
    extractionConfidence: 0.75,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(5000),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
        confidenceNotes: "Tiered: $5,000–$7,999 DD earns $350; higher tiers up to $450.",
      },
    ],
    disqualifiers: [{ disqualifierType: "existing_customer", lookbackMonths: 12 }],
  },
  {
    brandName: "Wells Fargo",
    legalName: "Wells Fargo Bank, N.A.",
    charterType: "national_bank",
    hqState: "CA",
    chexsystemsSensitivity: "moderate",
    productName: "Wells Fargo Everyday Checking",
    productType: "checking",
    monthlyFeeCents: c(10),
    accountOpeningUrl: "https://accountoffers.wellsfargo.com/checkingoffer/",
    applicationUrl: "https://accountoffers.wellsfargo.com/checkingoffer/",
    applicationChannel: "web",
    signupNotes:
      "Enroll through the offer page (needed to attach the $325). $1,000+ in qualifying electronic/ACH deposits within 90 days.",
    title: "Wells Fargo Everyday Checking — $325 bonus",
    bonusType: "cash",
    bonusAmountCents: c(325),
    offerEndDate: "2026-10-13",
    requirementWindowDays: 90,
    payoutWindowDays: 30,
    newCustomerRequired: true,
    termsUrl: "https://accountoffers.wellsfargo.com/checkingoffer/",
    sourceUrl: "https://www.doctorofcredit.com/wells-fargo-325-checking-bonus-available-online/",
    extractionConfidence: 0.85,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(1000),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "probabilistic",
        confidenceNotes: "$1,000+ in qualifying electronic deposits within 90 days.",
      },
    ],
    disqualifiers: [{ disqualifierType: "existing_customer", lookbackMonths: 12 }],
  },
  {
    brandName: "PNC Bank",
    legalName: "PNC Bank, National Association",
    charterType: "national_bank",
    hqState: "PA",
    chexsystemsSensitivity: "moderate",
    productName: "PNC Virtual Wallet with Performance Select",
    productType: "checking",
    monthlyFeeCents: c(25),
    accountOpeningUrl: "https://www.pnc.com/en/personal-banking/banking/virtual-wallet.html",
    applicationUrl: "https://www.pnc.com/en/personal-banking/banking/virtual-wallet.html",
    applicationChannel: "web",
    signupNotes: "$500 DD earns $100; $5,000 DD earns the full $400. Bonus credited 60–90 days after conditions met.",
    title: "PNC Virtual Wallet Performance Select — $400 bonus",
    bonusType: "cash",
    bonusAmountCents: c(400),
    offerEndDate: "2026-08-31",
    requirementWindowDays: 60,
    payoutWindowDays: 90,
    newCustomerRequired: true,
    termsUrl: "https://www.pnc.com/en/personal-banking/banking/virtual-wallet.html",
    sourceUrl: "https://www.cnbc.com/select/best-checking-account-bonuses/",
    extractionConfidence: 0.82,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(5000),
        windowDays: 60,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
        confidenceNotes: "$500 DD earns $100; $5,000 DD earns $400.",
      },
    ],
  },
  {
    brandName: "BMO",
    legalName: "BMO Bank N.A.",
    charterType: "national_bank",
    hqState: "IL",
    chexsystemsSensitivity: "moderate",
    productName: "BMO Smart Advantage Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.bmo.com/en-us/main/personal/checking-accounts/",
    applicationUrl: "https://www.bmo.com/en-us/main/personal/checking-accounts/",
    applicationChannel: "web",
    signupNotes: "$4,000 cumulative DD within 90 days. Cash bonus posts ~100 days after account opening.",
    title: "BMO Smart Advantage Checking — $400 bonus",
    bonusType: "cash",
    bonusAmountCents: c(400),
    offerEndDate: "2026-09-08",
    requirementWindowDays: 90,
    payoutWindowDays: 100,
    newCustomerRequired: true,
    termsUrl: "https://www.bmo.com/en-us/main/personal/checking-accounts/",
    sourceUrl: "https://www.nerdwallet.com/banking/best/bank-bonuses-and-promotions",
    extractionConfidence: 0.75,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(4000),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
  },
  // ---- Regional but includes Georgia (web application) -------------------
  {
    brandName: "Fifth Third Bank",
    legalName: "Fifth Third Bank, National Association",
    charterType: "national_bank",
    hqState: "OH",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["OH", "FL", "GA", "IL", "IN", "KY", "MI", "NC", "TN", "WV"],
    productName: "Fifth Third Momentum Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.53.com/content/fifth-third/en/personal-banking/bank/checking/momentum-checking.html",
    applicationUrl: "https://www.53.com/content/fifth-third/en/personal-banking/bank/checking-accounts.html",
    applicationChannel: "web",
    signupNotes: "$500+ in qualifying direct deposits within 90 days. Available in the Fifth Third footprint (incl. GA).",
    title: "Fifth Third Momentum Checking — $300 bonus",
    bonusType: "cash",
    bonusAmountCents: c(300),
    requirementWindowDays: 90,
    payoutWindowDays: 45,
    newCustomerRequired: true,
    termsUrl: "https://www.firstcard.app/learn/fifth-third-checking-account-bonus",
    sourceUrl: "https://www.firstcard.app/learn/fifth-third-checking-account-bonus",
    extractionConfidence: 0.78,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
    geoEligibleStates: ["OH", "FL", "GA", "IL", "IN", "KY", "MI", "NC", "TN", "WV"],
  },
  {
    brandName: "Truist",
    legalName: "Truist Bank",
    charterType: "state_bank",
    hqState: "NC",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["GA", "NC", "SC", "VA", "FL", "TN", "AL", "MD", "TX", "NJ", "PA"],
    productName: "Truist One Checking",
    productType: "checking",
    monthlyFeeCents: c(12),
    accountOpeningUrl: "https://www.truist.com/checking",
    applicationUrl: "https://www.truist.com/checking",
    applicationChannel: "web",
    signupNotes:
      "Amount/terms indicative — confirm the current Truist promo and promo code on the offer page before applying.",
    title: "Truist One Checking — $400 bonus",
    bonusType: "cash",
    bonusAmountCents: c(400),
    requirementWindowDays: 90,
    payoutWindowDays: 60,
    newCustomerRequired: true,
    termsUrl: "https://www.truist.com/checking-accounts",
    sourceUrl: DOC,
    extractionConfidence: 0.55,
    verificationStatus: "unverified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "probabilistic",
        confidenceNotes: "Amount/terms indicative — confirm current Truist promo at source.",
      },
    ],
    geoEligibleStates: ["GA", "NC", "SC", "VA", "FL", "TN", "AL", "MD", "TX", "NJ", "PA"],
  },
  // ---- App-only neobank (corrected to real terms) ------------------------
  {
    brandName: "Varo Bank",
    legalName: "Varo Bank, N.A.",
    charterType: "national_bank",
    hqState: "UT",
    chexsystemsSensitivity: "none",
    productName: "Varo Bank Account",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://apps.apple.com/us/app/varo-bank-mobile-banking/id1145550444",
    applicationUrl: "https://apps.apple.com/us/app/varo-bank-mobile-banking/id1145550444",
    applicationChannel: "app",
    signupNotes:
      "APP-ONLY — there is no web signup; open the account in the Varo mobile app (App Store / Google Play). The $150 bonus is REFERRAL-GATED (sign up via a referral link) and requires $500+ in qualifying direct deposits within 45 days. Qualifying DD = paycheck / pension / government benefits; Venmo, P2P, and Varo-routing transfers do NOT count.",
    title: "Varo Bank Account — $150 bonus (app-only)",
    bonusType: "cash",
    bonusAmountCents: c(150),
    requirementWindowDays: 45,
    payoutWindowDays: 7,
    newCustomerRequired: true,
    termsUrl: "https://www.varomoney.com/",
    sourceUrl:
      "https://www.doctorofcredit.com/varo-money-online-bank-account-75-sign-up-bonus-ios-android-sharing-referrals-still-a-nono/",
    extractionConfidence: 0.7,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 45,
        depositSourceConstraint: "payroll_ach",
        verificationDifficulty: "probabilistic",
        confidenceNotes:
          "Qualifying DD = paycheck/pension/govt benefits only; P2P and Varo-routing transfers excluded.",
      },
    ],
    disqualifiers: [
      {
        disqualifierType: "prior_bonus_lookback",
        detail: "Bonus requires a referral link and a new Varo account.",
      },
    ],
  },
  // ---- Real offers NOT available in Georgia (validator excludes them) ----
  {
    brandName: "Citibank",
    legalName: "Citibank, N.A.",
    charterType: "national_bank",
    hqState: "NY",
    chexsystemsSensitivity: "moderate",
    productName: "Citi Regular Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.citi.com/banking/special-offers",
    applicationUrl: "https://www.citi.com/banking/special-offers",
    applicationChannel: "web",
    signupNotes:
      "Enhanced Direct Deposits (electronic ACH — Zelle/Venmo/PayPal via ACH count). Available only in select Citi markets (not GA).",
    title: "Citi Enhanced Direct Deposit Checking — $325 bonus",
    bonusType: "cash",
    bonusAmountCents: c(325),
    requirementWindowDays: 90,
    payoutWindowDays: 30,
    newCustomerRequired: true,
    termsUrl: "https://bankbonus.com/promotions/citibank/citi-enhanced-direct-deposits-checking-bonus/",
    sourceUrl: "https://www.doctorofcredit.com/citi-300-checking-bonus/",
    extractionConfidence: 0.85,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(3000),
        targetCount: 2,
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
        confidenceNotes: "Two Enhanced Direct Deposits totaling $3,000+ (Zelle/Venmo/PayPal ACH count).",
      },
    ],
    disqualifiers: [
      {
        disqualifierType: "state_excluded",
        includedStatesOnly: ["NY", "CT", "MD", "VA", "DC", "CA", "NV", "NJ", "FL", "IL"],
        detail: "Available only in select Citi markets.",
      },
    ],
    geoEligibleStates: ["NY", "CT", "MD", "VA", "DC", "CA", "NV", "NJ", "FL", "IL"],
  },
  {
    brandName: "TD Bank",
    legalName: "TD Bank, N.A.",
    charterType: "national_bank",
    hqState: "NJ",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["ME", "NH", "VT", "MA", "RI", "CT", "NY", "NJ", "PA", "DE", "MD", "DC", "VA", "NC", "SC", "FL"],
    productName: "TD Beyond Checking",
    productType: "checking",
    monthlyFeeCents: c(25),
    accountOpeningUrl: "https://www.td.com/us/en/personal-banking/checking-accounts",
    applicationUrl: "https://www.td.com/us/en/personal-banking/checking-accounts",
    applicationChannel: "web",
    signupNotes: "$2,500 DD within 60 days. East-Coast footprint only (Maine–Florida); not GA.",
    title: "TD Beyond Checking — $300 bonus",
    bonusType: "cash",
    bonusAmountCents: c(300),
    requirementWindowDays: 60,
    newCustomerRequired: true,
    termsUrl: "https://www.td.com/us/en/personal-banking/checking-accounts",
    sourceUrl: "https://www.bankrate.com/banking/best-bank-account-bonuses-and-promotions/",
    extractionConfidence: 0.8,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(2500),
        windowDays: 60,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
    geoEligibleStates: ["ME", "NH", "VT", "MA", "RI", "CT", "NY", "NJ", "PA", "DE", "MD", "DC", "VA", "NC", "SC", "FL"],
  },
  {
    brandName: "KeyBank",
    legalName: "KeyBank National Association",
    charterType: "national_bank",
    hqState: "OH",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["OH", "NY", "PA", "WA", "OR", "CO", "UT", "ID", "ME", "VT", "CT", "IN", "MI", "AK"],
    productName: "Key Smart Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.key.com/personal/checking-accounts.jsp",
    applicationUrl: "https://www.key.com/personal/checking-accounts.jsp",
    applicationChannel: "web",
    signupNotes: "Enter promo code KDMA0526 at application; $2,000 DD within 90 days. KeyBank footprint only (not GA).",
    title: "KeyBank Smart Checking — $300 bonus",
    offerCode: "KDMA0526",
    bonusType: "cash",
    bonusAmountCents: c(300),
    requirementWindowDays: 90,
    newCustomerRequired: true,
    termsUrl: "https://www.key.com/personal/checking-accounts.jsp",
    sourceUrl: DOC,
    extractionConfidence: 0.72,
    verificationStatus: "llm_verified",
    requirements: [
      { requirementType: "promo_code_entry", isBonusGating: true, confidenceNotes: "Enter code KDMA0526 at application." },
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(2000),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
    geoEligibleStates: ["OH", "NY", "PA", "WA", "OR", "CO", "UT", "ID", "ME", "VT", "CT", "IN", "MI", "AK"],
  },
  {
    brandName: "Huntington",
    legalName: "The Huntington National Bank",
    charterType: "national_bank",
    hqState: "OH",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["OH", "MI", "IN", "IL", "WI", "MN", "PA", "WV", "KY", "CO", "SD", "NC", "SC"],
    productName: "Huntington Perks Checking",
    productType: "checking",
    monthlyFeeCents: c(10),
    accountOpeningUrl: "https://www.huntington.com/checking-account-promotions-bonuses-offers",
    applicationUrl: "https://www.huntington.com/checking-account-promotions-bonuses-offers",
    applicationChannel: "web",
    signupNotes: "$500 DD within 90 days and keep the account open 90 days. Midwest footprint only (not GA).",
    title: "Huntington Perks Checking — $400 bonus",
    bonusType: "cash",
    bonusAmountCents: c(400),
    requirementWindowDays: 90,
    payoutWindowDays: 14,
    newCustomerRequired: true,
    termsUrl: "https://www.huntington.com/checking-account-promotions-bonuses-offers",
    sourceUrl: "https://www.huntington.com/checking-account-promotions-bonuses-offers",
    extractionConfidence: 0.8,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
      { requirementType: "maintain_days", targetCount: 90, windowDays: 90, verificationDifficulty: "deterministic" },
    ],
    geoEligibleStates: ["OH", "MI", "IN", "IL", "WI", "MN", "PA", "WV", "KY", "CO", "SD", "NC", "SC"],
  },
  {
    brandName: "Associated Bank",
    legalName: "Associated Bank, N.A.",
    charterType: "national_bank",
    hqState: "WI",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["WI", "IL", "MN"],
    productName: "Associated Bank Balanced Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www.associatedbank.com/checking-account-bonus-offer-promotion",
    applicationUrl: "https://www.associatedbank.com/checking-account-bonus-offer-promotion",
    applicationChannel: "web",
    signupNotes: "$500 DD within 90 days. WI/IL/MN only (not GA).",
    title: "Associated Bank Checking — $300 bonus",
    bonusType: "cash",
    bonusAmountCents: c(300),
    requirementWindowDays: 90,
    newCustomerRequired: true,
    termsUrl: "https://www.associatedbank.com/checking-account-bonus-offer-promotion",
    sourceUrl: "https://www.associatedbank.com/checking-account-bonus-offer-promotion",
    extractionConfidence: 0.7,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
    geoEligibleStates: ["WI", "IL", "MN"],
  },
  {
    brandName: "M&T Bank",
    legalName: "Manufacturers and Traders Trust Company",
    charterType: "state_bank",
    hqState: "NY",
    chexsystemsSensitivity: "moderate",
    footprintStates: ["NY", "NJ", "PA", "MD", "DE", "VA", "WV", "CT", "MA", "DC", "ME", "NH", "VT"],
    productName: "M&T EZChoice Checking",
    productType: "checking",
    monthlyFeeCents: 0,
    accountOpeningUrl: "https://www3.mtb.com/personal/bank-accounts/checking",
    applicationUrl: "https://www3.mtb.com/personal/bank-accounts/checking",
    applicationChannel: "web",
    signupNotes: "Promo code + $500 DD within 90 days. Northeast footprint only (not GA).",
    title: "M&T Bank Checking — $200 bonus",
    bonusType: "cash",
    bonusAmountCents: c(200),
    offerEndDate: "2026-09-30",
    requirementWindowDays: 90,
    newCustomerRequired: true,
    termsUrl: "https://www3.mtb.com/personal/bank-accounts/checking",
    sourceUrl: DOC,
    extractionConfidence: 0.7,
    verificationStatus: "llm_verified",
    requirements: [
      {
        requirementType: "direct_deposit_cumulative",
        targetAmountCents: c(500),
        windowDays: 90,
        depositSourceConstraint: "any_ach",
        verificationDifficulty: "deterministic",
      },
    ],
    geoEligibleStates: ["NY", "NJ", "PA", "MD", "DE", "VA", "WV", "CT", "MA", "DC", "ME", "NH", "VT"],
  },
];
